In [15]:
import numpy as np
import os

In [20]:
SERIES_DIR_NAME = './WorldModels/data/series/'

In [2]:
data = np.load('WorldModels/data/series/694147997.npz')

In [3]:
for key in data.keys():
    print(key)

muS
log_varS
muB
log_varB
action
reward
done


## Checking if there are any [0 inf nans] in variance, and any [inf nans] in mu

In [35]:
file_size = 0
for root, dirs, files in os.walk(SERIES_DIR_NAME):
    for filename in files:
#         print(filename)
        file_size = file_size +1
        
print(file_size)

1549


In [21]:
def get_filelist(N):
    filelist = os.listdir(SERIES_DIR_NAME)
    filelist = [x for x in filelist if x != '.DS_Store']
    filelist.sort()
    length_filelist = len(filelist)

    if length_filelist > N:
      filelist = filelist[:N]

    if length_filelist < N:
      N = length_filelist

    return filelist, N

In [36]:
filelist, N = get_filelist(file_size)

In [69]:
indices = np.random.permutation(N)

z_listS = []
z_listB = []
muS_list =[]
muB_list =[]
log_varS_list = []
log_varB_list = []

for i in indices:
    new_data = np.load(SERIES_DIR_NAME + filelist[i])

    muS = new_data['muS']
    log_varS = new_data['log_varS']
    muB = new_data['muB']
    log_varB = new_data['log_varB']

    s = log_varS.shape

    zS = muS + np.exp(log_varS/2.0) * np.random.randn(*s)
    zB = muB + np.exp(log_varB/2.0) * np.random.randn(*s)
#     print('{} {} {} {}'.format(np.sum(np.isnan(muS)), np.sum(np.isnan(log_varS)),np.sum(np.isnan(muB)) ,np.sum(np.isnan(log_varB))))
#     print('{} {}'.format(log_varS, log_varB))

    z_listS.append(zS)
    z_listB.append(zB)
    muS_list.append(muS)
    muB_list.append(muB)
    log_varS_list.append(log_varS)
    log_varB_list.append(log_varB)
    
    
z_listS = np.array(z_listS)
z_listB = np.array(z_listB)
muS_list = np.array(muS_list)
muB_list = np.array(muB_list)
log_varS_list = np.array(log_varS_list)
log_varB_list = np.array(log_varB_list)

## Check for nans or infs in all of those lists

In [70]:
np.nan + 10

nan

In [71]:
np.inf + 10

inf

In [72]:
print(np.sum(np.sum(z_listS)))
print(np.sum(np.sum(z_listB)))
print(np.sum(np.sum(muS_list)))
print(np.sum(np.sum(muB_list)))
print(np.sum(np.sum(log_varS_list)))
print(np.sum(np.sum(log_varB_list)))

-257901610.218
316853096418.0
-2.66364e+08
-4.13582e+08
-1.66014e+06
1.62345e+07


## Check if there is zero in both log_variance lists

In [147]:
np.sum(np.abs(log_varS) <= 10e-3)

3

In [90]:
k = 0
for i in indices:
    for j in range(300):
        for k in range(32):
            if(np.abs(log_varS_list[i, j, 0, k ]) <= 1e-10):
                print(log_varS_list[i, j, 0, k ])
                k = k + 1
#         muS_list
#         muB_list

In [110]:
tol_list = [1e-1,1e-2,1e-3,1e-4,1e-5, 1e-6, 1e-7, 1e-8, 1e-9]

In [112]:
for tol in tol_list:
    print('_' * 24)
    print(tol)
    print(np.sum(np.abs(log_varS_list) <= tol) / log_varS_list.size * 100.0)
    print(np.sum(np.abs(log_varB_list) <= tol) / log_varB_list.size * 100.0)
    print('_' * 24)


________________________
0.1
1.14503308586
0.513651280396
________________________
________________________
0.01
0.115941736604
0.0508325263611
________________________
________________________
0.001
0.0111227673768
0.00498305358296
________________________
________________________
0.0001
0.000961641919518
0.000484183344093
________________________
________________________
1e-05
6.72476866796e-05
3.36238433398e-05
________________________
________________________
1e-06
6.72476866796e-06
0.0
________________________
________________________
1e-07
0.0
0.0
________________________
________________________
1e-08
0.0
0.0
________________________
________________________
1e-09
0.0
0.0
________________________


## Check if there is zero in zS and zB

In [113]:
for tol in tol_list:
    print('_' * 24)
    print(tol)
    print(np.sum(np.abs(z_listS) <= tol) / log_varS_list.size * 100)
    print(np.sum(np.abs(z_listS) <= tol) / log_varB_list.size * 100)
    print('_' * 24)


________________________
0.1
0.0315458898214
0.0315458898214
________________________
________________________
0.01
0.00315391650527
0.00315391650527
________________________
________________________
0.001
0.000248816440714
0.000248816440714
________________________
________________________
0.0001
1.34495373359e-05
1.34495373359e-05
________________________
________________________
1e-05
0.0
0.0
________________________
________________________
1e-06
0.0
0.0
________________________
________________________
1e-07
0.0
0.0
________________________
________________________
1e-08
0.0
0.0
________________________
________________________
1e-09
0.0
0.0
________________________


## Finally, the code for skipping on samples in indices 

In [114]:
indices = np.random.permutation(N)

z_listS = []
z_listB = []
muS_list =[]
muB_list =[]
log_varS_list = []
log_varB_list = []

for i in indices:
    new_data = np.load(SERIES_DIR_NAME + filelist[i])

    muS = new_data['muS']
    log_varS = new_data['log_varS']
    muB = new_data['muB']
    log_varB = new_data['log_varB']

    s = log_varS.shape

    zS = muS + np.exp(log_varS/2.0) * np.random.randn(*s)
    zB = muB + np.exp(log_varB/2.0) * np.random.randn(*s)
    
    

    z_listS.append(zS)
    z_listB.append(zB)
    muS_list.append(muS)
    muB_list.append(muB)
    log_varS_list.append(log_varS)
    log_varB_list.append(log_varB)
    
z_listS = np.array(z_listS)
z_listB = np.array(z_listB)
muS_list = np.array(muS_list)
muB_list = np.array(muB_list)
log_varS_list = np.array(log_varS_list)
log_varB_list = np.array(log_varB_list)

In [109]:
log_varS.shape

(300, 1, 32)

In [132]:
found_indicesS = (np.sum(abs(log_varS) <= 5e-2, axis = 2))[:,0]

In [133]:
found_indicesB = (np.sum(abs(log_varB) <= 5e-2, axis = 2))[:,0]

In [140]:
found_indicesS + found_indicesB

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 2, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0])

In [139]:
log_varS[found_indices == 0, :, :].shape

(282, 1, 32)

In [81]:
muS_list[0,:,0,:].shape

(300, 32)

## Ignore this 

In [86]:
10e-3

0.01

In [141]:
zS.shape

(300, 1, 32)

In [59]:
np.nan + 10

nan

In [10]:
np.sum(np.isnan(data['log_varB']))

0

In [34]:
data['muS'].shape

(300, 1, 32)

In [35]:
data['log_varS'].shape

(300, 1, 32)

In [36]:
data['muB'].shape

(300, 1, 32)

In [37]:
data['log_varB'].shape

(300, 1, 32)

In [38]:
data['action'].shape

(300, 3)

In [39]:
data['action'][0]

array([-0.0397011 ,  0.8833212 ,  0.69708145], dtype=float32)

In [40]:
data['reward'].shape

(300,)

In [41]:
data['done'].shape

(300,)

In [42]:
data['done']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
reward=  data['reward']

In [10]:
print(reward.shape)

(300,)


In [14]:
reward_1 = np.expand_dims(reward, axis = 1)

In [15]:
reward_2 = np.expand_dims(reward_1, axis = 2)

In [16]:
reward_2.shape

(300, 1, 1)

In [18]:
rew_list = []

for i in range(5):
    rew_list.append(reward_2)

In [19]:
rew_list = np.array(rew_list)


In [20]:
rew_list.shape

(5, 300, 1, 1)

In [31]:
rew_list[:, :-1,:].shape

(5, 299, 1, 1)